export const categories = [
   {title: "Акции", id: 1},
   {title: "Электроника", id: 2},
   {title: "Компютеры и сети", id: 3},
   {title: "Бытовая техника", id: 4},
   {title: "Стройка и ремонт", id: 5},
   {title: "Дом и сад", id: 6},
   {title: "Авто и мото", id: 7},
   {title: "Красота и спорт", id: 8},
   {title: "Детям и мамам", id: 9},
   {title: "Работа и офис", id: 10}
]

export const subCategories = [
     {title: "sub_cat_1_1", id: 1, cat_id: 1},
     {title: "sub_cat_1_2", id: 2, cat_id: 1},
     {title: "sub_cat_1_3", id: 3, cat_id: 1},
     {title: "sub_cat_2_1", id: 4, cat_id: 2},
     {title: "sub_cat_2_2", id: 5, cat_id: 2},
     {title: "sub_cat_2_3", id: 6, cat_id: 2},
     {title: "sub_cat_3_1", id: 7, cat_id: 3},
     {title: "sub_cat_3_2", id: 8, cat_id: 3},
     {title: "sub_cat_3_3", id: 9, cat_id: 3},
     {title: "sub_cat_4_1", id: 10, cat_id: 4},
     {title: "sub_cat_4_2", id: 11, cat_id: 4},
     {title: "sub_cat_4_3", id: 12, cat_id: 4},
     {title: "sub_cat_5_1", id: 13, cat_id: 5},
     {title: "sub_cat_5_2", id: 14, cat_id: 5},
     {title: "sub_cat_5_3", id: 15, cat_id: 5},
     {title: "sub_cat_6_1", id: 16, cat_id: 6},
     {title: "sub_cat_6_2", id: 17, cat_id: 6},
     {title: "sub_cat_6_3", id: 18, cat_id: 6},
     {title: "sub_cat_7_1", id: 19, cat_id: 7},
     {title: "sub_cat_7_2", id: 20, cat_id: 7},
     {title: "sub_cat_7_3", id: 21, cat_id: 7},
     {title: "sub_cat_8_1", id: 22, cat_id: 8},
     {title: "sub_cat_8_2", id: 23, cat_id: 8},
     {title: "sub_cat_8_3", id: 24, cat_id: 8},
     {title: "sub_cat_9_1", id: 25, cat_id: 9},
     {title: "sub_cat_9_2", id: 26, cat_id: 9},
     {title: "sub_cat_9_3", id: 27, cat_id: 9},
     {title: "sub_cat_10_1", id: 28, cat_id: 10},
     {title: "sub_cat_10_2", id: 29, cat_id: 10},
     {title: "sub_cat_10_3", id: 30, cat_id: 10},
]

export const ItemProduct = [
  {title: "item_product_1", id: 1, sub_cat_id: 1, price: 799,},
  {title: "item_product_2", id: 2, sub_cat_id: 2, price: 1349},
  {title: "item_product_3", id: 3, sub_cat_id: 3, price: 1399},
  {title: "item_product_4", id: 4, sub_cat_id: 4, price: 599},
  {title: "item_product_5", id: 5, sub_cat_id: 5, price: 599},
  {title: "item_product_6", id: 6, sub_cat_id: 6, price: 6000},
  {title: "item_product_7", id: 7, sub_cat_id: 7, price: 5000},
  {title: "item_product_8", id: 8, sub_cat_id: 8, price: 2000},
  // {title: "item_product_9", id: 9, sub_cat_id: 9},
  // {title: "item_product_10", id: 10, sub_cat_id: 10},
  // {title: "item_product_11", id: 11, sub_cat_id: 11},
  // {title: "item_product_12", id: 12, sub_cat_id: 12},
  // {title: "item_product_13", id: 13, sub_cat_id: 13},
  // {title: "item_product_14", id: 14, sub_cat_id: 14},
  // {title: "item_product_15", id: 15, sub_cat_id: 15},
  // {title: "item_product_16", id: 16, sub_cat_id: 16},
  // {title: "item_product_17", id: 17, sub_cat_id: 17},
  // {title: "item_product_18", id: 18, sub_cat_id: 18},
  // {title: "item_product_19", id: 19, sub_cat_id: 19},
  // {title: "item_product_20", id: 20, sub_cat_id: 20},
  // {title: "item_product_21", id: 21, sub_cat_id: 21},
  // {title: "item_product_22", id: 22, sub_cat_id: 22},
  // {title: "item_product_23", id: 23, sub_cat_id: 23},
  // {title: "item_product_24", id: 24, sub_cat_id: 24},
  // {title: "item_product_25", id: 25, sub_cat_id: 25},
  // {title: "item_product_26", id: 26, sub_cat_id: 26},
  // {title: "item_product_27", id: 27, sub_cat_id: 27},
  // {title: "item_product_28", id: 28, sub_cat_id: 28},
  // {title: "item_product_29", id: 29, sub_cat_id: 29},
  // {title: "item_product_30", id: 30, sub_cat_id: 30},
]

